DROP TABLE AllStaff CASCADE CONSTRAINTS;
CREATE TABLE AllStaff (
    staffID CHAR(5) NOT NULL,
    officeID CHAR(5) NOT NULL,
    fName VARCHAR(15) NOT NULL,
    lName VARCHAR(15) NOT NULL,
    phoneNo NUMBER(10),
    strAddres VARCHAR2(30),
    city VARCHAR2(15),
    zipCode CHAR(5),
    gender CHAR(1),
    DOB DATE NOT NULL,
    salary NUMBER(8,2) NOT NULL,
    mgrFlag CHAR(1),
    adminFlag CHAR(1),
    ownerFlag CHAR(1),
    driverFlag CHAR(1),
    driversLicense VARCHAR2(9),
    CONSTRAINTS AllStaff_PK PRIMARY KEY (staffID),
    CONSTRAINTS AllStaff_Sex_CK CHECK (gender IN ('f','m'))
);

DROP TABLE Contract CASCADE CONSTRAINTS;
CREATE TABLE Contract (
	contractID CHAR(5) NOT NULL,
	clientID CHAR(5) NOT NULL,
	officeID CHAR(5) NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	contractPrice CHAR(6) NOT NULL,
	CONSTRAINTS Contract_PK PRIMARY KEY (contractID)
);

DROP TABLE Drivers CASCADE CONSTRAINTS;
CREATE TABLE Drivers (
    staffID CHAR(5) NOT NULL,
    licensePlateNo VARCHAR2(9) NOT NULL,
    CONSTRAINTS Driver_PK PRIMARY KEY (staffID, licensePlateNo)
);

DROP TABLE Job CASCADE CONSTRAINTS;
CREATE TABLE Job (
	jobID CHAR(5) NOT NULL,
	staffID CHAR(5) NOT NULL,
	licensePlateNo VARCHAR2(9) NOT NULL,
	contractID CHAR(5) DEFAULT NULL,
	clientID CHAR(5) NOT NULL,
	jobDate DATE NOT NULL,
	jobPrice CHAR(6) DEFAULT NULL, -- contracts excluded
	jobMiles CHAR(4) NOT NULL, -- all jobs will have a mileage
	CONSTRAINTS Job_PK PRIMARY KEY (jobID)
);

DROP TABLE Office CASCADE CONSTRAINTS;
CREATE TABLE Office (
    officeID CHAR(5) NOT NULL,
    mgrStaffNo CHAR(5),
    name VARCHAR2(15) NOT NULL,
    strAddress VARCHAR2(30),
    city VARCHAR2(15),
    zipCode CHAR(5),
    phoneNo NUMBER(10),
    CONSTRAINTS Office_PK PRIMARY KEY (officeID)
);


DROP TABLE Client CASCADE CONSTRAINTS;
CREATE TABLE Client (
	clientID CHAR(5) NOT NULL,
	officeID CHAR(5) NOT NULL,
	fName VARCHAR(15) DEFAULT NULL,
	lName VARCHAR(15) DEFAULT NULL,
	businessName VARCHAR(20) DEFAULT NULL,
	clientGender CHAR(1) DEFAULT 'n',
	clientDOB DATE DEFAULT NULL,
	clientAddress VARCHAR(30) NOT NULL,
	clientCity VARCHAR(15) DEFAULT 'South Park',
	CONSTRAINTS ClientID_PK PRIMARY KEY (clientID)
);

DROP TABLE Taxi CASCADE CONSTRAINTS;
CREATE TABLE Taxi (
    licensePlateNo VARCHAR2(9),
    make VARCHAR2(15) NOT NULL,
    model VARCHAR2(8),
    year CHAR(4) NOT NULL,
    color VARCHAR2(10),
    inService CHAR(1),
    ownerID CHAR(5) NOT NULL,
    CONSTRAINTS Taxi_PK PRIMARY KEY (licensePlateNo),
    CONSTRAINTS Taxi_inService_CK CHECK (inService IN ('y','n'))
);

ALTER TABLE AllStaff
    ADD CONSTRAINTS AllStaff_officeID_FK FOREIGN KEY (officeID) REFERENCES Office(officeID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Client
	ADD CONSTRAINTS Client_officeID_FK FOREIGN KEY (officeID) REFERENCES Office (officeID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Contract
	ADD CONSTRAINTS Client_FK FOREIGN KEY(clientID) REFERENCES Client(clientID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Contract
	ADD CONSTRAINTS OfficeContract_FK FOREIGN KEY(officeID) REFERENCES Office(officeID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Drivers
    ADD CONSTRAINTS Driver_staffID_FK FOREIGN KEY (staffID) REFERENCES AllStaff(staffID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Job
	ADD CONSTRAINTS PlateNumber_FK FOREIGN KEY (licensePlateNo) REFERENCES Taxi (licensePlateNo)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

-- foreign key for Drivers table
ALTER TABLE Job
	ADD CONSTRAINTS StaffID_FK FOREIGN KEY (staffID) REFERENCES AllStaff(staffID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

-- foreign key for Client table
ALTER TABLE Job
	ADD CONSTRAINTS clientID_FK FOREIGN KEY (clientID) REFERENCES Client (clientID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

-- foreign key for Contract table
ALTER TABLE Job
	ADD CONSTRAINTS ContractID_FK FOREIGN KEY (contractID) REFERENCES Contract (contractID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE Taxi
    ADD CONSTRAINTS Taxi_ownerID_FK FOREIGN KEY (ownerID) REFERENCES AllStaff(staffID)
ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
