-- Name: Eric Blasko
-- ID:   005670557

DROP TABLE Hotel CASCADE CONSTRAINTS;
CREATE TABLE Hotel (
    hotelNo CHAR(4) NOT NULL,
    hotelName VARCHAR2(15) NOT NULL,
    city VARCHAR2(25), 
    CONSTRAINTS Hotel_PK PRIMARY KEY (hotelNo)
);

DROP TABLE Room CASCADE CONSTRAINTS;
CREATE TABLE Room (
    roomNo CHAR(4) NOT NULL,
    hotelNo CHAR(4),
    Rtype VARCHAR2(15) NOT NULL,
    price INT,
    CONSTRAINTS Room_PK PRIMARY KEY (roomNo,hotelNo)
);

ALTER TABLE Room
    ADD CONSTRAINTS Room_hotelNo_FK FOREIGN KEY (hotelNo) REFERENCES Hotel(hotelNo)
    ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;


DROP TABLE Booking CASCADE CONSTRAINTS;
CREATE TABLE Booking (
    hotelNo CHAR(4),
    guestNo CHAR(4),
    dateFrom DATE,
    dateTo DATE,
    roomNo CHAR(4),
    CONSTRAINTS Booking_PK PRIMARY KEY (hotelNo,guestNo,dateFrom)
);

ALTER TABLE Booking
    ADD CONSTRAINTS Booking_hotelNo_FK FOREIGN KEY (hotelNo) REFERENCES Hotel(hotelNo)
    ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

DROP TABLE Guest CASCADE CONSTRAINTS;
CREATE TABLE Guest (
    guestNo CHAR(4) NOT NULL,
    guestName VARCHAR2(20) NOT NULL,
    guestAddress VARCHAR2(50),
    CONSTRAINTS Guest_PK PRIMARY KEY (guestNo)
);

ALTER TABLE Booking
    ADD CONSTRAINTS Booking_guestNo_FK FOREIGN KEY (guestNo) REFERENCES Guest(guestNo)
    ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;



